### ISSUE TITLE
Marinebon.org is down

### ISSUE THREAD

**Issue by superjai** [marinebon/old_marinebon.github.io#19]
Marinebon.org is down, as thhere seems to be something wrong with the security certificate:
NET::ERR_CERT_COMMON_NAME_INVALID
![Screen Shot 2022-08-03 at 1 53 30 PM](https://user-images.githubusercontent.com/1744300/182709678-303a3a42-c946-4877-8134-0acf1f888cd2.png)

**Comment by 7yl4r** [comment]
You caught us in the middle of flipping a switch. The new site should be up and secured now.
