### ISSUE TITLE
Analytics?

### ISSUE THREAD

**Issue by torieketcham** [marinebon/old_marinebon.github.io#6]
Hi @7yl4r - am I right in thinking that we don't have analytics tools installed on this site? Gabrielle has asked me if it's possible to provide some insights.

**Comment by 7yl4r** [comment]
You are correct. 
We don't have anything right now, but I think that google analytics is pretty easy to add.

**Comment by torieketcham** [comment]
Thanks. I just added it - when you have a moment, do you mind checking the config file just to confirm that it looks right to you?

**Comment by 7yl4r** [comment]
Oh! That's even easier than I was thinking.
Looks great to me!

Is data showing up yet in analytics.google.com?
________________________________

**Comment by torieketcham** [comment]
No data yet... I'll check tomorrow!

**Comment by torieketcham** [comment]
Hmm still nothing yet. I assume something should have shown up by now, don't you?

**Comment by 7yl4r** [comment]
I would have thought so.
I don't see any detailed directions in the IOOS page or in the "minimal mistakes" template.
I wonder what we might be missing.

**Comment by torieketcham** [comment]
I made some changes to the config file after reading through some issues on the MM GitHub. Not sure if they will make a difference but we'll see!

![Screen Shot 2020-05-20 at 8 09 36 AM](https://user-images.githubusercontent.com/44508950/82444732-aea12600-9a71-11ea-8a90-bb6ae79bd7e5.png)

**Comment by torieketcham** [comment]
Looks like it's working now! Going to close this issue.

![Screen Shot 2020-05-21 at 9 19 56 AM](https://user-images.githubusercontent.com/44508950/82563030-525b0680-9b44-11ea-93cc-d4fd2969105c.png)
